export interface Article {
  id: string;
  title: string;
  summary: string;
  category: Category;
  imageUrl: string;
  author: string;
  timestamp: string;
  content?: string; // Optional full content, can be generated by AI
  isBreaking?: boolean;
}

export enum Category {
  World = 'World',
  Politics = 'Politics',
  Business = 'Business',
  Tech = 'Tech',
  Health = 'Health',
  Entertainment = 'Entertainment',
  Style = 'Style',
  Travel = 'Travel',
  Sports = 'Sports',
  Video = 'Video',
}

export type ViewState = 
  | { type: 'HOME' }
  | { type: 'CATEGORY'; category: Category }
  | { type: 'ARTICLE'; articleId: string };